language: elixir
matrix:

  # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Compatibility%20and%20Deprecations.md

  # Elixir 1.9

  - elixir: 1.9.2
    otp_release: 20.3

  - elixir: 1.9.2
    otp_release: 21.0

  - elixir: 1.9.2
    otp_release: 22.0

env:
- MIX_ENV=test COVERALLS_ELIXIR_VERSION=1.9.2 COVERALLS_OTP_RELEASE=22.0
script:
- mix test
after_script:
- ./coveralls.sh

